import "./reset.css";
import "./globals.css";
import "./github-markdown-dark.css";

export const metadata = {
  title: "Michell Brito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
  